import pandas as pd
import numpy as np
from typing import Tuple, List, Optional


def load_raw_data(csv_path: str) -> pd.DataFrame:
    """
    Load the raw CSV generated by scripts/generate_data.py.

    Args:
        csv_path (str): Path to the raw CSV file.

    Returns:
        pd.DataFrame: Loaded dataframe.
    """
    return pd.read_csv(csv_path)


def clean_equilend_data(
    df: pd.DataFrame,
    *,
    numeric_cols: Optional[List[str]] = None,
    categorical_cols: Optional[List[str]] = None,
    outlier_clip_quantiles: Tuple[float, float] = (0.01, 0.99),
) -> pd.DataFrame:
    """
    Clean the EquiLend synthetic dataset.

    This function is designed for the CSV produced by scripts/generate_data.py and
    performs the following steps:
    - Ensures expected columns exist.
    - Coerces numeric columns to numeric dtype and drops rows with invalid values.
    - Handles missing values in numeric columns via median imputation.
    - Handles missing values in categorical columns via mode imputation.
    - Clips numeric outliers to a reasonable quantile range to avoid extreme values.

    Args:
        df (pd.DataFrame): Raw dataframe.
        numeric_cols (Optional[List[str]]): List of numeric column names. If None,
            sensible defaults based on the generator script are used.
        categorical_cols (Optional[List[str]]): List of categorical column names. If None,
            sensible defaults based on the generator script are used.
        outlier_clip_quantiles (Tuple[float, float]): Lower and upper quantiles used
            to clip outliers in numeric columns.

    Returns:
        pd.DataFrame: Cleaned dataframe, ready for modeling.
    """
    df = df.copy()

    # Default column sets based on scripts/generate_data.py
    if numeric_cols is None:
        numeric_cols = [
            "monthly_income",
            "utility_bill_average",
            "repayment_history_pct",
        ]
    if categorical_cols is None:
        categorical_cols = [
            "gender",
            "employment_length",
        ]

    expected_columns = set(numeric_cols + categorical_cols + ["default_status"])
    missing_expected = expected_columns.difference(df.columns)
    if missing_expected:
        raise ValueError(f"Missing expected columns in input data: {missing_expected}")

    # Ensure numeric columns are actually numeric and drop rows that cannot be coerced.
    for col in numeric_cols + ["default_status"]:
        df[col] = pd.to_numeric(df[col], errors="coerce")

    # Drop rows where target is missing or invalid
    df = df.dropna(subset=["default_status"])

    # Handle missing values in numeric columns using median imputation.
    for col in numeric_cols:
        median_val = df[col].median()
        df[col] = df[col].fillna(median_val)

    # Handle missing values in categorical columns using mode imputation.
    for col in categorical_cols:
        if col in df.columns:
            mode_series = df[col].mode(dropna=True)
            if not mode_series.empty:
                mode_val = mode_series.iloc[0]
                df[col] = df[col].fillna(mode_val)

    # Clip numeric outliers to the specified quantile range to keep values realistic.
    lower_q, upper_q = outlier_clip_quantiles
    for col in numeric_cols:
        col_lower = df[col].quantile(lower_q)
        col_upper = df[col].quantile(upper_q)
        df[col] = df[col].clip(lower=col_lower, upper=col_upper)

    return df


def load_and_clean(csv_path: str) -> pd.DataFrame:
    """
    Convenience helper to load a CSV from disk and return a cleaned dataframe.

    Args:
        csv_path (str): Path to the raw EquiLend CSV.

    Returns:
        pd.DataFrame: Cleaned dataframe.
    """
    raw = load_raw_data(csv_path)
    return clean_equilend_data(raw)

